issuer: https://dex.example.com

storage:
  type: kubernetes
  config:
    inCluster: true

web:
  http: 0.0.0.0:5556
  # For production, use HTTPS
  # https: 0.0.0.0:5554
  # tlsCert: /etc/dex/tls/tls.crt
  # tlsKey: /etc/dex/tls/tls.key

# Configuration for telemetry
telemetry:
  http: 0.0.0.0:5558

staticClients:
- id: 3d65cff418b45c057d8be201240f5e8a
  name: 'kubectl SSH OIDC Plugin'
  secret: YpWPCFkIX/KZUgoSKvxMj6Oefe9E6WJWQYKamWTkY/A=

# SSH connector configuration
connectors:
- type: ssh
  id: ssh
  name: SSH Key Authentication
  config:
    # Map users to their SSH public keys
    users:
      "john.doe":
        keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExample... john.doe@example.com"
          - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9Example... john.doe@example.com"
        username: "john.doe"
        email: "john.doe@example.com"
        full_name: "John Doe"
        groups:
          - "developers"
          - "kubernetes-users"

      "jane.smith":
        keys:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAnotherExample... jane.smith@example.com"
        username: "jane.smith"
        email: "jane.smith@example.com"
        full_name: "Jane Smith"
        groups:
          - "admins"
          - "kubernetes-admins"
    
    # JWT issuers that are allowed
    allowed_issuers:
    - "kubectl-ssh-oidc"
    
    # Default groups for all authenticated users
    default_groups:
    - "authenticated"
    
    # Token TTL in seconds (1 hour)
    token_ttl: 3600

# Enable CORS for web-based clients
web:
  allowedOrigins: ['*']

# Enable the grpc API. This is required for some clients.
grpc:
  addr: 0.0.0.0:5557
  # For production, use TLS
  # tlsCert: /etc/dex/tls/server.crt
  # tlsKey: /etc/dex/tls/server.key
  # tlsCA: /etc/dex/tls/ca.crt

logger:
  level: "debug"
  format: "text"