name: CI

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

env:
  GO_VERSION: '1.24'

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  test:
    name: Test and Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Semver
      uses: paulhatch/semantic-version@v5.4.0
      with:
        bump_each_commit: true
        tag_prefix: ""
        format: "${major}.${minor}.${patch}"
      id: semver

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Download dependencies
      run: go mod download

    - name: Run unit tests first
      run: make test

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        verify: false

    - name: Run linting
      run: make lint

    # - name: Run integration tests
    #   run: make test-integration
    #   timeout-minutes: 10

    - name: Upload test logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-logs-${{ github.run_id }}
        path: |
          test/integration/*.log
          /tmp/kubectl-ssh-oidc-integration-*/
        retention-days: 7

    - name: Clean up integration environment
      if: always()
      run: make clean-integration

    - name: Tag Repo
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ steps.semver.outputs.version_tag }}
        tag_prefix: ""

    - name: Publish Release  
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.semver.outputs.version_tag }}
        name: ${{ steps.semver.outputs.version_tag }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}