name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{steps.semver.outputs.version_tag}}
    
    steps:
    - uses: actions/checkout@v4

    - name: Semver
      uses: paulhatch/semantic-version@v5.1.0
      with:
        bump_each_commit: true
      id: semver
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.7'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
    
    - name: Run tests
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v4
    #   with:
    #     file: ./coverage.txt
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     verbose: true

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Tag Repo
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{secrets.TAGGING_PAT}}
          custom_tag: ${{needs.test.outputs.semver}}
          tag_prefix: ""

      - name: Publish Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TAGGING_PAT }}
        with:
          tag_name: ${{needs.test.outputs.semver}}
          release_name: ${{needs.test.outputs.semver}}
          draft: false
          prerelease: false